# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QGridLayout,
    QGroupBox, QLabel, QLineEdit, QListView,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QRadioButton, QSizePolicy, QSpinBox,
    QStatusBar, QTextBrowser, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(796, 849)
        MainWindow.setMinimumSize(QSize(796, 849))
        font = QFont()
        font.setFamilies([u"Noto Sans"])
        font.setPointSize(9)
        font.setBold(False)
        MainWindow.setFont(font)
        self.actionAddExcelFile = QAction(MainWindow)
        self.actionAddExcelFile.setObjectName(u"actionAddExcelFile")
        icon = QIcon(QIcon.fromTheme(u"x-office-spreadsheet"))
        self.actionAddExcelFile.setIcon(icon)
        self.actionSetSavePath = QAction(MainWindow)
        self.actionSetSavePath.setObjectName(u"actionSetSavePath")
        icon1 = QIcon(QIcon.fromTheme(u"document-save"))
        self.actionSetSavePath.setIcon(icon1)
        self.actionSetGlobalPassword = QAction(MainWindow)
        self.actionSetGlobalPassword.setObjectName(u"actionSetGlobalPassword")
        icon2 = QIcon(QIcon.fromTheme(u"dialog-password"))
        self.actionSetGlobalPassword.setIcon(icon2)
        self.actionCancelWork = QAction(MainWindow)
        self.actionCancelWork.setObjectName(u"actionCancelWork")
        icon3 = QIcon(QIcon.fromTheme(u"edit-undo"))
        self.actionCancelWork.setIcon(icon3)
        self.actionUndoCancel = QAction(MainWindow)
        self.actionUndoCancel.setObjectName(u"actionUndoCancel")
        icon4 = QIcon(QIcon.fromTheme(u"edit-redo"))
        self.actionUndoCancel.setIcon(icon4)
        self.actionSetOutputEncryption = QAction(MainWindow)
        self.actionSetOutputEncryption.setObjectName(u"actionSetOutputEncryption")
        icon5 = QIcon(QIcon.fromTheme(u"system-lock-screen"))
        self.actionSetOutputEncryption.setIcon(icon5)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(660, 560, 120, 23))
        self.progressBar.setValue(24)
        self.grpFile = QGroupBox(self.centralwidget)
        self.grpFile.setObjectName(u"grpFile")
        self.grpFile.setGeometry(QRect(10, 10, 210, 380))
        self.listFileAdded = QListView(self.grpFile)
        self.listFileAdded.setObjectName(u"listFileAdded")
        self.listFileAdded.setGeometry(QRect(10, 30, 190, 340))
        self.listFileAdded.setAcceptDrops(True)
        self.listFileAdded.setDragEnabled(True)
        self.listFileAdded.setDragDropMode(QAbstractItemView.DragDropMode.InternalMove)
        self.listFileAdded.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.grpSheet = QGroupBox(self.centralwidget)
        self.grpSheet.setObjectName(u"grpSheet")
        self.grpSheet.setGeometry(QRect(230, 10, 210, 380))
        self.listSheetInFile = QListView(self.grpSheet)
        self.listSheetInFile.setObjectName(u"listSheetInFile")
        self.listSheetInFile.setGeometry(QRect(10, 30, 190, 340))
        self.listSheetInFile.setDragEnabled(True)
        self.listSheetInFile.setDragDropMode(QAbstractItemView.DragDropMode.DragOnly)
        self.listSheetInFile.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.grpSheetToMerge = QGroupBox(self.centralwidget)
        self.grpSheetToMerge.setObjectName(u"grpSheetToMerge")
        self.grpSheetToMerge.setGeometry(QRect(475, 10, 210, 380))
        self.listSheetToMerge = QListView(self.grpSheetToMerge)
        self.listSheetToMerge.setObjectName(u"listSheetToMerge")
        self.listSheetToMerge.setGeometry(QRect(10, 30, 190, 340))
        self.listSheetToMerge.setAcceptDrops(True)
        self.listSheetToMerge.setDragEnabled(True)
        self.listSheetToMerge.setDragDropMode(QAbstractItemView.DragDropMode.InternalMove)
        self.listSheetToMerge.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.btnSheetToMergeAdd = QPushButton(self.centralwidget)
        self.btnSheetToMergeAdd.setObjectName(u"btnSheetToMergeAdd")
        self.btnSheetToMergeAdd.setGeometry(QRect(440, 150, 35, 35))
        self.btnSheetToMergeRemove = QPushButton(self.centralwidget)
        self.btnSheetToMergeRemove.setObjectName(u"btnSheetToMergeRemove")
        self.btnSheetToMergeRemove.setGeometry(QRect(440, 200, 35, 35))
        self.grpSavePath = QGroupBox(self.centralwidget)
        self.grpSavePath.setObjectName(u"grpSavePath")
        self.grpSavePath.setGeometry(QRect(10, 470, 771, 80))
        self.btnBrowsePath = QPushButton(self.grpSavePath)
        self.btnBrowsePath.setObjectName(u"btnBrowsePath")
        self.btnBrowsePath.setGeometry(QRect(660, 40, 94, 26))
        self.lineEditSavePath = QLineEdit(self.grpSavePath)
        self.lineEditSavePath.setObjectName(u"lineEditSavePath")
        self.lineEditSavePath.setGeometry(QRect(20, 40, 631, 26))
        self.txtLogOutput = QTextBrowser(self.centralwidget)
        self.txtLogOutput.setObjectName(u"txtLogOutput")
        self.txtLogOutput.setGeometry(QRect(10, 600, 771, 192))
        self.lblCurrentFile = QLabel(self.centralwidget)
        self.lblCurrentFile.setObjectName(u"lblCurrentFile")
        self.lblCurrentFile.setGeometry(QRect(10, 560, 641, 18))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(230, 390, 210, 90))
        self.layoutWidget = QWidget(self.groupBox_2)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(15, 26, 188, 56))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.radioButtonAll = QRadioButton(self.layoutWidget)
        self.radioButtonAll.setObjectName(u"radioButtonAll")

        self.gridLayout.addWidget(self.radioButtonAll, 0, 0, 1, 1)

        self.radioButtonChoice = QRadioButton(self.layoutWidget)
        self.radioButtonChoice.setObjectName(u"radioButtonChoice")

        self.gridLayout.addWidget(self.radioButtonChoice, 0, 1, 1, 1)

        self.radioButtonSpecific = QRadioButton(self.layoutWidget)
        self.radioButtonSpecific.setObjectName(u"radioButtonSpecific")

        self.gridLayout.addWidget(self.radioButtonSpecific, 1, 0, 1, 1)

        self.lineEditSheetSpecific = QLineEdit(self.layoutWidget)
        self.lineEditSheetSpecific.setObjectName(u"lineEditSheetSpecific")

        self.gridLayout.addWidget(self.lineEditSheetSpecific, 1, 1, 1, 1)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(695, 10, 90, 131))
        self.layoutWidget1 = QWidget(self.groupBox)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(18, 30, 54, 90))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.radioButtonSheet = QRadioButton(self.layoutWidget1)
        self.radioButtonSheet.setObjectName(u"radioButtonSheet")

        self.verticalLayout_2.addWidget(self.radioButtonSheet)

        self.radioButtonHorizontal = QRadioButton(self.layoutWidget1)
        self.radioButtonHorizontal.setObjectName(u"radioButtonHorizontal")

        self.verticalLayout_2.addWidget(self.radioButtonHorizontal)

        self.radioButtonVertical = QRadioButton(self.layoutWidget1)
        self.radioButtonVertical.setObjectName(u"radioButtonVertical")

        self.verticalLayout_2.addWidget(self.radioButtonVertical)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(695, 150, 90, 240))
        self.spinBoxEmpty = QSpinBox(self.groupBox_3)
        self.spinBoxEmpty.setObjectName(u"spinBoxEmpty")
        self.spinBoxEmpty.setGeometry(QRect(20, 110, 50, 30))
        self.label = QLabel(self.groupBox_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 140, 90, 90))
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.layoutWidget2 = QWidget(self.groupBox_3)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(20, 40, 50, 62))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.checkBoxEmptyrow = QCheckBox(self.layoutWidget2)
        self.checkBoxEmptyrow.setObjectName(u"checkBoxEmptyrow")

        self.verticalLayout_3.addWidget(self.checkBoxEmptyrow)

        self.checkBoxEmptyColumn = QCheckBox(self.layoutWidget2)
        self.checkBoxEmptyColumn.setObjectName(u"checkBoxEmptyColumn")

        self.verticalLayout_3.addWidget(self.checkBoxEmptyColumn)

        self.btnStart = QPushButton(self.centralwidget)
        self.btnStart.setObjectName(u"btnStart")
        self.btnStart.setGeometry(QRect(695, 400, 90, 80))
        font1 = QFont()
        font1.setFamilies([u"Noto Sans"])
        font1.setPointSize(11)
        font1.setBold(False)
        self.btnStart.setFont(font1)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(480, 390, 160, 90))
        self.widget = QWidget(self.groupBox_4)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 29, 142, 50))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.radioButtonOriginalBoth = QRadioButton(self.widget)
        self.radioButtonOriginalBoth.setObjectName(u"radioButtonOriginalBoth")

        self.verticalLayout.addWidget(self.radioButtonOriginalBoth)

        self.radioButtonOriginalSheet = QRadioButton(self.widget)
        self.radioButtonOriginalSheet.setObjectName(u"radioButtonOriginalSheet")

        self.verticalLayout.addWidget(self.radioButtonOriginalSheet)

        MainWindow.setCentralWidget(self.centralwidget)
        self.grpSavePath.raise_()
        self.progressBar.raise_()
        self.grpFile.raise_()
        self.grpSheet.raise_()
        self.grpSheetToMerge.raise_()
        self.btnSheetToMergeAdd.raise_()
        self.btnSheetToMergeRemove.raise_()
        self.txtLogOutput.raise_()
        self.lblCurrentFile.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.btnStart.raise_()
        self.groupBox_4.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 796, 23))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.actionAddExcelFile)
        self.menu.addAction(self.actionSetSavePath)
        self.menu.addAction(self.actionCancelWork)
        self.menu.addAction(self.actionUndoCancel)
        self.menu_2.addAction(self.actionSetGlobalPassword)
        self.menu_2.addAction(self.actionSetOutputEncryption)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAddExcelFile.setText(QCoreApplication.translate("MainWindow", u"\uc5d1\uc140\ud30c\uc77c \ucd94\uac00", None))
        self.actionSetSavePath.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\uacbd\ub85c \uc124\uc815", None))
        self.actionSetGlobalPassword.setText(QCoreApplication.translate("MainWindow", u"\uc804\uc5ed \ube44\ubc00\ubc88\ud638 \uc124\uc815", None))
        self.actionCancelWork.setText(QCoreApplication.translate("MainWindow", u"\uc791\uc5c5 \ucde8\uc18c", None))
        self.actionUndoCancel.setText(QCoreApplication.translate("MainWindow", u"\ucde8\uc18c \ub418\ub3cc\ub9ac\uae30", None))
        self.actionSetOutputEncryption.setText(QCoreApplication.translate("MainWindow", u"\ucd9c\ub825\ud30c\uc77c \uc554\ud638\ud654 \uc124\uc815", None))
        self.grpFile.setTitle(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \ubaa9\ub85d", None))
        self.grpSheet.setTitle(QCoreApplication.translate("MainWindow", u"\uc2dc\ud2b8 \ubaa9\ub85d", None))
        self.grpSheetToMerge.setTitle(QCoreApplication.translate("MainWindow", u"\ubcd1\ud569 \ubaa9\ub85d", None))
        self.btnSheetToMergeAdd.setText(QCoreApplication.translate("MainWindow", u"\u25b6", None))
        self.btnSheetToMergeRemove.setText(QCoreApplication.translate("MainWindow", u"\u25c0", None))
        self.grpSavePath.setTitle(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5 \uc704\uce58", None))
        self.btnBrowsePath.setText(QCoreApplication.translate("MainWindow", u"\ucc3e\uc544\ubcf4\uae30", None))
        self.lblCurrentFile.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\uc77c\uad04\ucc98\ub9ac", None))
        self.radioButtonAll.setText(QCoreApplication.translate("MainWindow", u"\ubaa8\ub4e0 \uc2dc\ud2b8", None))
        self.radioButtonChoice.setText(QCoreApplication.translate("MainWindow", u"\uc9c1\uc811 \uc120\ud0dd", None))
        self.radioButtonSpecific.setText(QCoreApplication.translate("MainWindow", u"\ud2b9\uc815 \uc2dc\ud2b8", None))
        self.lineEditSheetSpecific.setText(QCoreApplication.translate("MainWindow", u"\ucf64\ub9c8(,)\ub85c \uad6c\ubd84", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\ubcd1\ud569 \ubc29\uc2dd", None))
        self.radioButtonSheet.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\ud2b8", None))
        self.radioButtonHorizontal.setText(QCoreApplication.translate("MainWindow", u"\uc138\ub85c", None))
        self.radioButtonVertical.setText(QCoreApplication.translate("MainWindow", u"\uac00\ub85c", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\ub370\uc774\ud130 \uc815\ub9ac", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\uc785\ub825\ud55c \uac12 \uc774\uc0c1<br/>\ubc18\ubcf5\ub418\ub294<br/>\ube44\uc5b4\uc788\ub294 \ud589/\uc5f4<br/>\uc790\ub3d9 \uc81c\uac70</p></body></html>", None))
        self.checkBoxEmptyrow.setText(QCoreApplication.translate("MainWindow", u"\ud589", None))
        self.checkBoxEmptyColumn.setText(QCoreApplication.translate("MainWindow", u"\uc5f4", None))
        self.btnStart.setText(QCoreApplication.translate("MainWindow", u"\uc791\uc5c5 \uc2dc\uc791(F5)", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\uc2dc\ud2b8 \uc774\ub984 \uaddc\uce59", None))
        self.radioButtonOriginalBoth.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8\ud30c\uc77c\uba85_\uc6d0\ubcf8\uc2dc\ud2b8\uba85", None))
        self.radioButtonOriginalSheet.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8\uc2dc\ud2b8\uba85", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\uc635\uc158", None))
    # retranslateUi

